### ISSUE TITLE
Example Branch 'Dialogue System' is not up to date with latest develop

### ISSUE THREAD

**Issue by game-libgdx-unity** [Seneral/Node_Editor_Framework#133]
Steps I have done:
1. Create new project with Unity 5.5
2. Clone develop branch, copy the cloned folder to the project (No error)
2. Clone Dialogue System branch, copy the cloned folder to the project (15 errors)

![image](https://user-images.githubusercontent.com/5079800/28001351-091cfe32-6556-11e7-8577-986c7d51878d.png)

Please help me, thank you so much!

**Comment by Seneral** [comment]
Hey, 
the example vranch hasn't beem uodated with tge latest changes yet (which were alot). If you're ok with the missing features you can go back a few weeak to dff7d93 and it should work:)
Seneral

**Comment by ChicK00o** [comment]
Will have a look at this on the coming weekend

**Comment by game-libgdx-unity** [comment]
Thank you so much for your answer, I tried the old commit, the errors have gone, but when I run the scene of example, it's just a black screen. Is this intended to happen?

I will tried older commit and let you know soon

![image](https://user-images.githubusercontent.com/5079800/28008872-6d79faba-6583-11e7-852a-83c3e854f42a.png)

**Comment by game-libgdx-unity** [comment]
I'm sorry for messing up, the example would run properly if we press 'L' key, but it;s still from the old commit

**Comment by Quyrean** [comment]
Hello,

I am new to the Node editor (really cool btw) and have updated the dialog editor example code to work with the latest dev branch and the new connection system.  What would be the procedure to post this for review if anyone wants it?  I am not very experienced with git and the examples being a different branch is confusing because there are not dev/main branches for the examples.

thanks,

Jen...

**Comment by Seneral** [comment]
Hey, that sounds great @Quyrean :) thanks!
It's indeed a bit complicated, especially if you've never done it before. Git repositories work through so called 'Pull Requests' which essentially is a request from anyone for his commit to be 'pulled' into the main branch he is targetting.
I assume you already done so, if not, fork this project (top right) so you have a own working copy of it, commit your changes to the example to your forked example branch (through command line or some GUI interface like SourceTree). You should then have a commit on your side and your example branch should be up to date with your changes. 
Then you can create a pull request from your branch to the main example branch of this repository through this online interface:)
If you need more info, look it up, it is complicated but there're planty of resources available online:)
Seneral

**Comment by Quyrean** [comment]
Ok, posted.  Thanks for the info.

**Comment by Seneral** [comment]
Sorry for not responding, things gotten in the way:)
Will try to take a look at it, but already looks solid. Thanks! :)
Seneral

**Comment by Seneral** [comment]
Thanks to @Quyrean , just merged his port:)
