### ISSUE TITLE
Additional overloads for Node.CreateInput with System.Type parameter instead of string

### ISSUE THREAD

**Issue by kpietraszko** [Seneral/Node_Editor_Framework#135]
Currently Node.CreateInput look like this: 
`public NodeInput CreateInput (string inputName, string inputType)`
Could we get an overload that takes: string inputName and System.Type inputType?
Same for Node.CreateOutput.

**Comment by Seneral** [comment]
Oh, sure, I forgot them...
They were build-in before the restructure:)
Try to make a commit this evening.
Seneral

**Comment by kpietraszko** [comment]
Thanks.
I'm a bit puzzled why types are stored in Dictionary<string, TypeData>, instead of Dictionary<Type, TypeData>

**Comment by Seneral** [comment]
Because it stores connection types (or ConnectionStyles after the restructure) that do not necessarily define a value connection but might just be for visual purposes and thus use an string identifier. With the type functions you can simply reference them by the type, too, of course. But lot's of people requested being able to style a connection without the (for them) useless typing and value handling, so it has been separated:)

**Comment by kpietraszko** [comment]
Oh ok. I guess that makes it more versatile. With System.Type overloads everyone will be happy 👍

**Comment by Seneral** [comment]
Just noticed, which version are you using? Definitely not the latest develop branch, which I was assuming...

**Comment by Seneral** [comment]
Adding it to the latest develop branch for now, will not update master for that though.
What you can do though is use typeof(Type).FullName instead, for both creation and adressing. Of course you can add these as wrappers yourself:) This will, if that ConnectionType is not defined somewhere, create a type automatically by itself:)
Seneral

**Comment by kpietraszko** [comment]
@Seneral I'm using master branch. I guess I will switch to develop branch. Thanks for your engagement in this project.

**Comment by Seneral** [comment]
Sure, think that's better. Although, lot's of changes, and lot's of manual adjustments of existing nodes needed since I reworked major systems recently... But definitely worth it:)
Seneral

**Comment by Seneral** [comment]
Implemented in 5962974:)
