### ISSUE TITLE
ImportExportStructure

### ISSUE THREAD

**Issue by AtheosCode** [Seneral/Node_Editor_Framework#137]
my customer node have some property ,it can be null. when click the Export, ImportExportStructure do not check null data and throw a error

`public ObjectData(object obj)
		{
			refID = obj.GetHashCode();
			type = obj.GetType();
			data = obj;
		}
`
obj sometime is null, you should check it

**Comment by Seneral** [comment]
Wow, can't believe that slipped through... thanks for the heads up! Will fix it along some other 'error' with strings soon:)

**Comment by AtheosCode** [comment]
![sp20170830_144029_936](https://user-images.githubusercontent.com/11506195/29858730-5bfb45d8-8d91-11e7-83e0-191a53e8ae72.png)

**Comment by Seneral** [comment]
Oh didn't know that, will take a look on how to fix that:)

**Comment by Seneral** [comment]
Also finally fixed both errors, hope it works now!:)
