### ISSUE TITLE
RTEditorGUI.EnumPopup

### ISSUE THREAD

**Issue by AtheosCode** [Seneral/Node_Editor_Framework#138]
when  use `panelType = (PanelType)RTEditorGUI.EnumPopup(panelType)` in cutom node in Unity Play model

![8w5 9p2 d gfw p jcoom76](https://user-images.githubusercontent.com/11506195/29858923-45047a88-8d92-11e7-84a7-f9b917496b08.png)

And I change to `EditorGUILayout.EnumPopup` it is ok. 

supplement:
I think the problem is here, It  retrurn a new GUIContent() every frame when Application isPlaying

> 

		public static System.Enum EnumPopup (GUIContent label, System.Enum selected) 
		{
			#if UNITY_EDITOR
			if (!Application.isPlaying)
				return UnityEditor.EditorGUILayout.EnumPopup (label, selected);
			#endif
			label.text += ": " + selected.ToString ();
			GUILayout.Label (label);
			return selected;
		}

**Comment by Seneral** [comment]
Yep seen that before but forgot to fix it, thanks:)
