### ISSUE TITLE
How to remove connections when using ConnectionCount.Multi?

### ISSUE THREAD

**Issue by RomanZhu** [Seneral/Node_Editor_Framework#145]
For example, i have that situation:

![ciwafnflrgirwrnvyokwtg](https://user-images.githubusercontent.com/12017366/33363617-3506a3f2-d4f2-11e7-9cc9-74ce8e1d289c.png)

And i want to remove one of connections.  As i see there is no way built-in :( 

I wrote dirty fix to get it semi-working and continue on writing extension

![dsoux64wrquuqpxcjbabjq](https://user-images.githubusercontent.com/12017366/33364074-e68fce22-d4f3-11e7-8460-b3a97c28f8bd.png)

Is there a way to remove connections which i'm missing? Like holding some button and dragging left mouse over wires? (Which is desired behavior, as it's used in many other applications)

**Comment by RomanZhu** [comment]
I'm using develop branch

**Comment by Seneral** [comment]
From multi connection knobs, there is unfortunately now way, no. 
Before the revamp, there were only Mult-Single connections so it was 'create froo multi and delete from single. Since that becake interchangeable, single-single connections were also supported, but for multi-multi a new concept was required. This is not yet implemented, but it will eb similar to what you said. Do you require multi-multi? Then I might try ti do tgat when I have time soon:)

**Comment by RomanZhu** [comment]
Yeah we need it :D
I can get away with my solution while developing extension, but i'll need properly working one at the end. 

What i'm doing is parsing UnityEvents from scene objects and building tree procedurally with custom nodes, then modifying those events when connections changes in node editor

**Comment by Seneral** [comment]
Ok, will try it at some point. Core is the hit detection for the bezier curves.
Then, what would you prefer? Clicking the curve to delete or dragging a line to detach all connections under it? Last would be nice but would require an additional key to hold...

**Comment by RomanZhu** [comment]
I prefer line-cuts  with preview of that line (if we dragging mouse and button).
Main reason for that is high possibility of random missed clicks.

Also it would be good to fast remove connection when clicking on them while holding same button (not too close to Knobs in case of multi connections (as that editor has no undo and random)

One more common way is selecting wire and deleting it by context menu or buttons

**Comment by RomanZhu** [comment]
https://youtu.be/XKbSu5PC8VA?t=633

Just to visualize what i mean

**Comment by Seneral** [comment]
Btw, you can check out #148, which is a good temporary workaround:)

**Comment by RomanZhu** [comment]
Yeah, i saw that :)
Will check it out tomorrow
