### ISSUE TITLE
More control over saving/loading

### ISSUE THREAD

**Issue by RomanZhu** [Seneral/Node_Editor_Framework#146]
I have node network which should always replicate actual state of components  of types "Type1" and "Type2" in the scene. Those types have UnityEvent, where **could be** links to instances of "Type1 or "Type2" or some random types (which are ignored)

I have nodes with types Type1Node and Type2Node, who has serializeble field of type Type1 and Type2 (to link to components they represent).

I have custom nodeCanvas. When canvas is empty it parses current scene and collects Type1 and Type2 instances. Then it generates nodes of needed types and fills links. So far so good.

1) As you see i have links to scene, so canvas of my type should be saved to **scene only** . But there is **no way built-in to limit saving functionality**

Just a suggestion to think about

**Comment by Seneral** [comment]
Yep could be some property on the node canvas you can override, which modifies the ContextMenu behaviour in NodeEditorInterface aswell as directly in the save function in NodeEditorSaveManager.
Don't know when I might do that but it's easy to add:)

**Comment by Seneral** [comment]
Added option to the canvas to only allow scene saving:) Hope that does it for you!
