### ISSUE TITLE
Popups inside node in zoomed canvas

### ISSUE THREAD

**Issue by RomanZhu** [Seneral/Node_Editor_Framework#153]
HI again :D

I have a problem, if i zoom in canvas, then my popups are drawing in wrong positions :(

How to fix it? I have one thing in mind - recreate popup using other GUI elements..

![9qz-fhjpt5klkjci5kzf5q](https://user-images.githubusercontent.com/12017366/34936783-b0dbc432-f9f3-11e7-841a-9e4711de8b20.png)
![zqmisft2sq_ud7toi2xj5w](https://user-images.githubusercontent.com/12017366/34936784-b1005ea0-f9f3-11e7-8b57-236a4675f01a.png)

How my nodes working - 
they create instance of CustomEditor for ReactionCollection class, so it's the same as in default inspector.
and then they draw it

_[CustomEditor(typeof(ReactionCollection))]
public class ReactionCollectionEditor2 : Editor_

![zr_3oghdtgatj6w-njc2ra](https://user-images.githubusercontent.com/12017366/34937047-72f0bcd0-f9f4-11e7-9189-412d66610b82.png)

**Comment by Seneral** [comment]
Ya, that's basically the core problem - the default popups do not support even the native scale, a shame really...
Only solution is, as you said, to replace them. I personally won't do that for some time though, sorry - basically, the custom GenericMenu could be extended / used to work as popups though:)
Seneral

**Comment by Seneral** [comment]
Closed because it is a known issue and internal Unity error...
