### ISSUE TITLE
Custom (Additional) Save format for Runtime

### ISSUE THREAD

**Issue by Seneral** [Seneral/Node_Editor_Framework#43]
**Description:** Current save format, ScriptableObjects, cannot be created and saved at runtime nor saved externally. So, a new save file format for runtime is needed. It should be optional for the Editor but essential for Runtime.
Maybe Binary, but more likely XML, just like Substance's .sbs.

**State:** None. Along with it there should be an attribute-based tagging system for extra variables that need to be saved in each Node/NodeKnob subtype. The rest is hardcoded as it is known what to save, obviously.
Please notify me before working on this to discuss some details:)

**Comment by WeslomPo** [comment]
Hi, before doing of that, need to understand how to load something :). I spent four hours by two days and still don't understand how to open window and create some nodes that I needed after opening windows. How it I can do? Saving something in some format really ease if we have some certain interfaces.

**Comment by Seneral** [comment]
How do you mean that? Do you mean adding nodes through the editor window interface? :D

**Comment by pmhpereira** [comment]
@WeslomPo, if you need a piece of code to add a Node, refer to [this comment](https://github.com/Baste-RainGames/Node_Editor/issues/55#issuecomment-189866119) I made to another user.

**Comment by Seneral** [comment]
Ah ok, you mean programmatically. There is an even simpler alternative to create nodes:
`SomeNodeType node = Node.Create (SomeNodeType.GetID, ScreenToGUIPos (Event.current.mousePosition)) as SomeNodeType;`

**Comment by WeslomPo** [comment]
@Seneral this not working :) 
`[MenuItem("Tools/VilEditor")]
public static void Open() {
	NodeEditorWindow.CreateEditor ();
	Node node = Node.Create ("Vil:Generator", new Vector2(100,100));
}`
:(

**Comment by Seneral** [comment]
Make sure you have set the canvas you want to place the node on as the current canvas (NodeEditor.curNodeCanvas) as mentioned before, this will only be done during the drawing phase or if you set it manually. It is not optimal, I know, might change that later on. Also make sure the node with the ID "Vil:Generator" exitsts if that is still not working;)

**Comment by WeslomPo** [comment]
@Seneral ok, I have done that moment, but it working not properly and some times throw an error that it has not a NodeType of "CalcNode.ID" type for example, and any other types.

**Comment by Seneral** [comment]
@WeslomPo Sorry, missed that the editor of course have to be initialized when you tryto call this directly after loading the window. Initializing is usually only done in the OnGUI function but it is possible elsewhere. Try calling `NodeEditor.ReInit (false);` which will tell the framework to load all resources and setup everything but the GUI part (which is only possible in OnGUI due to unity constraints)

**Comment by WeslomPo** [comment]
@Seneral works not perfectly, sometimes showing nothing, sometimes load as expected. 

Now I always catch exception when using a object value and that unload all nodes and breaks all progress. I commented code that clear data while catch exception and It began to work more tolerant, but all my node loose object values for some reason. :(

**Comment by Seneral** [comment]
Ok, if your doing it before the framework was initialized (in the Open function f.E.), use this:
``` C#
NodeEditor.ReInit (false); // Make sure the framework is initiated
_editor.AssureCanvas (); // Make sure a canvas is loaded
NodeEditor.curNodeCanvas = _editor.mainNodeCanvas; // Set the canvas to create the Node on as the current one

// Location is the canvas center (mouse pos won't work in creation)
CalcNode node = Node.Create (CalcNode.ID, Vector2.zero) as CalcNode; // Creating a calc node
Debug.Log (node.name);
```
if your using it in the GUI of the editor window when it's sure it is initiated and the canvas is existant, use something like this:
```C#
if (GUILayout.Button (new GUIContent ("Add my Node"))) 
{
	NodeEditor.curNodeCanvas = mainNodeCanvas;
	CalcNode node = Node.Create (CalcNode.ID, NodeEditor.ScreenToGUIPos (mainEditorState, Event.current.mousePosition)) as CalcNode;
	Debug.Log (node.name);
}
```
That should work, maybe the names vary a bit because I changed them in that area on my development copy....

**Comment by Seneral** [comment]
In addition I just noticed something odd, the first node would be a type mismatch in the save file. That's actually because the functionality to add the new node to the save file is done through a callback in NodeEditorWindow, the SetupCacheEvents, which is only called in OnEnable. Sou you would need to call the node creation afterwards, else you get a null node the first time the editor initializes...

**Comment by Seneral** [comment]
** Removed off-topic node creation discussion **

**Comment by Seneral** [comment]
New update: I'm finally working on this:)
State: Aleady far in, most stuff stands and is integrated:)

The goal is to allow fast and easy implementation of own formats, even for custom databases. So as with most systems, it is fully modular, just extend the ImportExportFormat base class and program the IO routines:) Also, you can easily add an interface if you need, say, special access to a custom database to import/export to. No big deal, just a few lines of code in the format declaration itself.

Also, the NodeCanvas is optionally served in a seperate, linked and structured data format which makes it easier to interface with alot of formats like XML. It removes the need for caring about unique IDs, linking and also finding custom node variable data. 
Variables are fetched from the nodes just like any other serialization system does, accounting for public/private and the [System.NonSerialized] and [SerializeField] attributes.

So, in the end, most work is lifted off the actual format-specific implementation. As with many systems in the framework, it only needs a single additional class to implement a custom data format, be it as complex as you want:)

I'll finish the custom knob system #74 first though because of the obvious structural changes it comes with. Don't want to modify the format right after implementing it:)

As always, feedback appreciated.
Seneral

**Comment by Seneral** [comment]
Finished this part aswell, import system is now fully functional with an XML format as a base:)
Once again, this can easily be extended to own formats or even custom database access:)
Will create a PR tomorrow...

**Comment by Seneral** [comment]
This too is finally merged and committed, would love to hear your feedback:)
Will keep this open for some days...
Seneral

**Comment by Seneral** [comment]
Alright, seems to run fine now:)
IO Formats have full support (see XML Format)...
Although I did not get feedback from users implementing custom formats or database accesses yet, I think it should prove fine:)
